id: AB0909874
base_file: fFC3E.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 18:03:35.569453
  last_modified_at: 2022-06-19 18:03:35.569465
